version: "3"

services:
  web:
    image: webdevops/php-apache:alpine-php7
    ports:
      - "4500:80"
      #Troca porta 4500
    volumes:
      - ./www:/app

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: lab_teste
      volumes:
        - ./volume-mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini

services:
  portainer:
    image: portainer/portainer
    deploy:
      placement:
        constraints: [node.role == maneger]
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "1"
    ports:
      - "9000:9000"
    volumes:
     - portainer_data:/data
     - /var/run/docker.sock:/var/run/docker.sock
      
volumes:
  portainer_data:
